### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#1212]
Modernize integration tests. 

Goal: concentrate on writing the feature testing logic that can be executed on any platform instead of writing platform-dependent mutations.

- [ ] Create a project that contains integration test cases for any kind of sensenet installation.
- [ ] Create test case classes containing platform-independent integration test methods.
- [ ] Create/generate platform-dependent classes that build repositories and calls test cases.
- [ ] Rewrite the existing tests.

To be considered:

- Every test case is a parameterless and void method.
- A test case needs to be platform-independent.
- Every test method is a testing framework called method (e.g. has [TestMethod] attr for MSTestFW).
- Test method needs to call the test case.
- More classes/files will be needed due to a large number of test cases.
- Investigate that the test methods can be programmatically generated from the test cases.
- Test methods will be generated from test cases minimum for the following platforms:
- Every platform-dependent test needs to be separated and consider to be rewritten to a generalized test case.
- It would be good if the existing unit tests (>1700) will be rewritten to the new system.
