### ISSUE TITLE
[META] IR Decoupling planning

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#123]
- [x] **8h** Generalize analyzers (need to use in querying).
- [ ] **4h** Use generalized configuration and analyzers (see indexing tasks).
- [ ] **12** [Finalizing API](https://github.com/SenseNet/sensenet/issues/166)
  - [ ] **4h** @kavics gathers API element in a textual format.
  - [ ] **2h** @tusmester reviews names, interfaces, main structures
  - [ ] **2h** @iviczl reviews names, interfaces, main structures
  - [ ] **4h** @kavics updates the API if needed
  - [ ] **16h** API code comment
- [ ] **12h** Centralized index component
  - [ ] _8h_ :() - Discussion about activity handling
  - [ ] _?h_ :() - Discussion about service architecture
  - [ ] _?h_ Centralized index component implementation
- [ ] **?40?h** Azure search implementation
- [ ] **40h** Lucene29 Check (acceptance and performance testing)
- [ ] Write additional integration tests with Lucene29 (move from budapest?).
    - [ ] **??** Integration tests (minimum sensenet services level).
    - [ ] **??16h** Click tests (let's see to work everything in lucene, sql and azure).
- [ ] **16h** [Develop Luc29SearchEngine](https://github.com/SenseNet/sensenet/issues/157)
    - [ ] **?h** committing issue
- [ ] **16h** Change index document serialization format from binary to json.
- [ ] **4h** Finalize the implementation slot in the StorageContext.Search.
- [ ] **1h** Remove all Lucene.Net references from sensenet except SnSearch.
- [ ] **??** Finalize indexing engine API (names and granularity, source files, project structure)
    - [ ] **??** General classes (e.g.: ContentQuery) go back to sensenet core from SearchImpl.
- [ ] **??** Remove/transform these (not API friendly) calls:
    - [ ] **??** StorageContext.Search.IsOuterEngineEnabled.
    - [ ] **??** StorageContext.Search.SearchEngine == InternalSearchEngine.Instance.
- [ ] **??** Implement Azure Indexing Engine
- [ ] **??** Write and measure performance with comparative tests (benchmark):
    - [ ] **??** A: Two webserver + distributed local indexes + messaging
    - [ ] **??** B: Two webserver + centralized index (Azure or test implementation)
- [ ] **??** Add/modify indexing an querying telemetry (SnTrace). 
- [ ] **40h** Latest Lucene engine implementation (if released)
  - [ ] **8h** Learn.
  - [ ] **16h** SnAST compiler (query object).
  - [ ] **16h** Query executor.

Additional tasks:
- Plan-B-Spike if the Azure is too slow (e.g. result cache, Lucene service etc.)
- Lucene search engine SERVICE if the Azure Search service isn't sufficient.
- Deployment / migration anything.
- Doc / info sharing.
