### ISSUE TITLE
Information Retrieval Renewal PROJECT

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#125]
- [x] Generalized search module
- [x] Decouple Lucene search engine from the content repository layer
- [x] Deployment / migration.
- [x] Doc / info sharing.
- [x] Lucene Search Service
