### ISSUE TITLE
Azure search indexing

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#143]
Implement the document handling in Azure search indexing

## Tasks
- [x] Document conversion
- [x] Implement the API.
   - [x] Add new
   - [x] update
   - [x] delete
- [x] Write the unit tests

## Acceptance crit
- [x] The unit tests succeed
