### ISSUE TITLE
Improve batch actions (copy, move, delete)

### ISSUE THREAD

**Issue by gallayl** [SenseNet/sensenet#147]
### Solution:
On the server side it seems to be the easiest solution to introduce a new overload for the Copy operation that actually returns the new node. This prevents breaking the current API. Than we can use this new overload in the Copy odata action to return all the info to the client that it needs.

Same goes for Move and Delete.

### Tasks:
- [x] Extend Node copy, move, delete API
- [x] Use this in OData actions
### Acceptance criteria:
- [x] gallayl is glad with the changes
- [x] The feature is tested and accepted by @gallayl 

#### Current behavior
The mentioned custom actions returns only a **200 OK** (without response body) or an **500** with a concatenated exception message and a serialized Exception.

#### Problem 1.
When copying content, we don't have *any* info about what content has been created. Assuming based on the target path and content name can be problematic because of an *incremental naming*

#### Problem 2.
We should get some detailed info if an operation has been partially succeeded, e.g. when copying 3 contents and one of them failed, we have to trigger 2 ContentCreated() and one ContentCreateFailed() events with the corresponding content data. We can't do that with the current implementation.

#### Suggestion
The actions should return detailed info (at least the NodeHeads from the *affected* and also from the *failed* operations) in the response in a similar format:
```json
{
   "d": {
       "__count": 3,
       "results": [
          { "Id": 101, "Path": "Root/Test/a", "Name": "a" }
          { "Id": 102, "Path": "Root/Test/b", "Name": "b" }
       ],
       "errors": [{
          "content": { "Id": 103, "Path": "Root/Test/C", "Name": "C" },
          "error": {
              "code": "NotSpecified",
              "exceptiontype": "Exception",
              "message": {
                  "lang": "en-us",
                  "value": "Cannot copy the content because the target folder already contains a content named  x1 .\\nCannot copy the content because the target folder already contains a content named  a3 .\\nCannot copy the content because the target folder already contains a content named  a4 ."
              },
              "innererror": {
                  "trace": "ODataException: Cannot copy the content because the target folder already contains a content named 'x1'.\r\nCannot copy the content because the target folder already contains a content named 'a3'.\r\nCannot copy the content because the target folder already contains a content named 'a4'.\r\n\r\n---- Inner Exception:\r\nException: Cannot copy the content because the target folder already contains a content named 'x1'.\r\nCannot copy the content because the target folder already contains a content named 'a3'.\r\nCannot copy the content because the target folder already contains a content named 'a4'.\r\n   at SenseNet.ApplicationModel.CopyBatchAction.Execute(Content content, Object[] parameters) in C:\\Dev\\github\\sensenet\\src\\Services\\ApplicationModel\\CopyBatchAction.cs:line 42\r\n   at SenseNet.Portal.OData.ODataFormatter.WriteOperationResult(Stream inputStream, PortalContext portalContext, ODataRequest odataReq) in C:\\Dev\\github\\sensenet\\src\\Services\\OData\\ODataFormatter.cs:line 426\r\n   at SenseNet.Portal.OData.ODataHandler.ProcessRequest(HttpContext context, String httpMethod, Stream inputStream) in C:\\Dev\\github\\sensenet\\src\\Services\\OData\\ODataHandler.cs:line 189\r\n=====================\r\n"
              }
          }
       }]
     }
}
```

**Comment by borsi** [comment]
This'll spawn some issues on monday.

**Comment by tusmester** [comment]
On the server side it seems to be the easiest solution to introduce a **new overload for the Copy operation** that actually **returns the new node**. This prevents breaking the current API. Than we can use this new overload in the Copy odata action to return all the info to the client that it needs.

**Comment by gallayl** [comment]
👍
