### ISSUE TITLE
Develop Luc29SearchEngine

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#157]
We should have an abstraction between the Content Query and the Lucene Query 

## Tasks
- [x] Execute content query over ISearchEngine
- [x] In-memory query engine
- [x] Ensure that the Repository can start with Lucene29SearchEngine
    - [x] Meeting that helps decide the place of calling the SqlQueryExecutor
    - [x] Resolve AutoFilter & TimespanFilter in the SnQuery before call IQueryEngine implementation
    - [x] Classify SnQuery instead of LucQuery
    - [x] Develop real IPermissionChecker.
    - [x] :() Meeting: destroy SqlQueryEngine or not.
        - [x] Create internal SqlQueryEngine.
        - [x] Choice query engine by query classification: SqlQueryExecutor or configured outer executor.
- [x] Save Node via the Lucene Search Engine
- [x] Create a diagram about the whole process and system
- [x] Refactor commiting into a commit manager class

## Acceptance crit
- [x] The Query engine is usable
  - [x] Indexing Unit Tests succeed
  - [x] Execute a query on an empty db and index - the resultset should be empty without any errors
  - [x] Insert contents that fit the previous query and rerun the query - the resultset should contain these contents
- [x] Borsi understands the diagram
