### ISSUE TITLE
'/Actions?scenario=something' does not return ODataApplications

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#161]
I try to implement a new ActionMenu component to list Actions of a Content by a Scenario but I get the Application type of Actions only.

## Steps to Reproduce

1. Login with Admin at [https://dmsservice.demo.sensenet.com](https://dmsservice.demo.sensenet.com)
2. Try the following [url](https://dmsservice.demo.sensenet.com/odata.svc/content(4467)/Actions?scenario=DMSListItem&$select=Id,Path,Name,Type,DisplayName,Description,Icon&metadata=no&$inlinecount=allpages)

## Expected Behavior
All the 6 Actions with the 'DMSListItem' scenario should be listed

## Actual Behavior
There're only 4 Actions listed (Rename, CopyTo, MoveTo and Delete) and two are missing (ShareContent and StarContent)

## Tasks
- [x] Add all available actions to the response - can be html and OData and client actions
- [x] Filter the actions list with the scenario url parameter, which can be a comma-separated list
- [x] Should work with the above-mentioned url ('/Actions...')
- [x] Should work expanded and with any kind of content request (with one or more content requested)

**Comment by tusmester** [comment]
Consider making this _Actions_ virtual field smarter, maybe using url parameters. Currently it returns only _html actions_.
