### ISSUE TITLE
Improve system start/stop

### ISSUE THREAD

**Issue by borsi** [SenseNet/sensenet#165]
## Tasks
- [x] Extend 'start' process by logging components overridden by code.
- [x] When stopping the system, all the subcomponents should be stopped as well
- [x] Lucene IndexDirectory should be linked with the Repository Instance
