### ISSUE TITLE
BUG: MongoDb ReaderStream overrun

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#298]
Open XML text extractor tries read more than available in TextExtractor.cs line:188.

**The bug**: the specification of the System,IO.Stream does not expect any exception if the Seek method oversteps the stream's Length.

**Tasks**:
- [x] Ensure that the Position can be greater than the Length after Seek called.
- [x] Ensure that the overseek does not throws any exception.
- [x] Ensure that the overseeked stream reads nothing.
