### ISSUE TITLE
Patching in the cloud

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#361]
## Goal
We aim to create a patch mechanism that is as **automated** as possible. Developers should be able to simply update the libraries from NuGet and start the application. The upgrade should happen at application start - if there is a patch available.

### Considerations
- We are concentraing on upgrading the **database**. 
- We do not have access to the actual web folder in the cloud, we can only upgrade libraries locally on the dev machine. After that the developer will _publish_ the new web folder to the staging and live environments.
- Old and new dlls and the content repository can be 'incompatible' in some cases. Features must _reduce the chance_ of this so that old and new app domains can connect to the _same database_.
- We patch components, the current Packaging table in the db seems to be sufficient.
- Features provide a patch for themselves (e.g. the MS SQL db provider).
- We have to determine the **order of patch execution**, because components may depend on each other. 

## Patch levels
Patches can be of different levels: some of them are simple and can be executed automatically while the repository is running, others require the full application to be stopped.

All patches need to run **exclusively**: no other patch can be executed on the same repository at the same time.

#### Level 1
> Old/new dbs and dlls are compatible.

- No conflict with anything.
- Can be executed independently, does not matter how many other app domains exist
- It is not mandatory to restart other app domains
- Messages may be sent during/after the patch to restart some components (e.g. loaded versioninfo, content type manager, etc).
- What about patch **dependencies**? In one app domain still one patch should run at the same time.

#### Level 2: locking the repository
> Old/new dbs and dlls are still somewhat compatible.

This patch changes the db schema or the content type system in a way that requires a write lock. When executing a patch in one app domain, the db should be locked and **other running app domains** should be **notified**.
- write lock: (depending on the patch) _all features_ need to be aware of this flag. 

#### Level 3: exclusive [LATER?]
This patch cannot be executed when other app domains are running, all other app domains and the whole content repository need to be shut down before executing the patch.

### RUNNING
We need to describe how a **running** app domain behaves during the execution of a patch (in a different app domain).
#### 1. Incompatible Content Type system
- [x] a missing content handler should not prevent loading other existing content types
#### 2. Incompatible feature
A missing type should not break the whole system. This is the responsibility of the feature.
- [ ] review a couple of features from this point of view

### RESTART
We need to describe how a **restarting** app domain behaves after the execution of a patch.
#### 1. All components have the same version as in the db
Nothing happens, repo starts correctly.
#### 2. Code version is older
_Currently_ this leads to an error. It is the responsibility of a feature to determine if it can work with a newer database.
- [ ] remove this restriction
#### 3. Code version is newer
- [ ] if there is a patch available (code resource or app resource), execute it

## Upgrade package
- type: _PATCH_, _INSTALL_
- version from/to (7.9-7.10)
- blocker or not
- OnBeforeRepository start steps (db changes, sql scripts)
- OnAfterRepository start steps

## SnComponent in code
- Supported version: the last component version that this code supports. If it is bigger than the current version in the db and there is no patch available, the component cannot run. _This should not prevent the system from starting! Only the feature should be unavailable_.

## New API
Create an api that will let us inject patch execution to the appropriate **life cycle point** of the app and **repository start**.
