### ISSUE TITLE
Indexing enum names

### ISSUE THREAD

**Issue by kavics** [SenseNet/sensenet#471]
Enum names are not indexed unless they are written in a localization file. 

**Expectation**: enum names should always be searchable. For example the following line should be a valid content query:
```csharp
public enum Enum1 { Value1, Value2, Value3 };
string query = $"FieldName:{Enum1.Value2}";
```
### Tasks
 - [ ] Enum names are searchable even if they are not localized.
 - [ ] Enum names are searchable even if they are localized but the enum name is different from localized texts.
- [x] Localized enum texts are also searchable.

### Test
The feature has two inactivated acceptance tests: 
```
Indexing_Choice_Enum_NotLocalized
Indexing_Choice_Enum_Localized.
```
