### ISSUE TITLE
Redesign roadmap

### ISSUE THREAD

**Issue by kultsar** [SenseNet/sensenet#509]
- [ ] decide if we want to redesign or not. Remain as is and keep assigning items to year's quarters and keep it modifying, or assign items to something like nearish, midterm, longterm categories
  - [ ] check out other product roadmaps (Trello and the other ones checked before and more)
  - [ ] check out roadmap tools
