### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by herflis** [SenseNet/sensenet#632]
Rethink, rewrite, restructure sensenet docs
- concepts
   - [x] overview (snaas overview diagram)
   - [x] what is headless cms
   - [ ] what is JAMstack
   - [ ] what is CMS as a service
   - [x] content
   - [ ] content management through REST API
   - [ ] content types
   - [ ] user and group management
   - [ ] roles
   - [ ] permissions
   - [ ] document preview
   - [ ] localization
   - [ ] settings
   - [ ] querying
   - [ ] workspaces
   - [ ] content templates
   - [ ] versioning
   - [ ] basic approval workflow
   - [ ] sharing
   - [ ] webhooks
   - [ ] authentication
- tutorials
   - [ ] explore 1000 content demo repository (as an enduser or as a developer)
   - [ ] create and explore your sn repository
   - [x] getting started with sensenet and react
   - [ ] getting started... .net client
   - [x] using sensenet in a react app
   - [x] deploy to netlify
   - [ ] authentication in js client
   - [ ] authentication in .net client
   - [ ] authentication in react app
- react sample apps
   - [ ] react project template
   - [ ] image gallery
   - [ ] todoapp
   - [ ] document browser
   - [ ] memo app
   - [ ] file upload demo
   - [ ] calendar demo
   - [ ] collaboration demo
   - [ ] sharing demo
- end user docs for admin-ui
   - [x] about using the admin ui in general
   - [x] command palette
   - [x] personal settings in general
   - [x] dashboard
   - [ ] permission related stuff (demo users, groups, accesses)
   - [x] settings/configs
   - [ ] version info/update versions
   - [ ] saved search and the search results page in general
   - [ ] content tree
   - [ ] users and groups
   - [ ] content types
   - [ ] localization related files
   - [ ] working with multiple repos
   - [ ] menu costumization in general
   - [ ] How to add a query basedmenu item and screen to the drawer
   - [ ] How to add a tree based menu item and screen to the drawer
   - [ ] How to add a custom menu item and screen to the drawer
- platform related docs
   - [ ] .net client
   - [ ] js client
   - [ ] react ui extensions
- API (odata/js/.net)
   - [ ] common API
   - [ ] content management API
   - [ ] document preview API
   - [ ] permission API
   - [ ] user and group management API
   - [ ] authentication
   - [ ] sharing API
   - [ ] query API
- about demos
   - [x] 1000 content demo

**Comment by ChiragAgarwal7** [comment]
can I work on the cms as a service doc?

**Comment by sakshamtaneja21** [comment]
may i know the link of repo
