### ISSUE TITLE
[Components]: Notification

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#77]
Create a repository (sn-notification) and NuGet packages for the **Notification feature**.

- [x] a dll-only package (_SenseNet.Notification_)
- [x] an install package (tables, content types, etc) (_SenseNet.Notification.Install_)
- [x] a GUI package for portlets. Dependency: _WebPages_ (_SenseNet.Notification.Portlets_)

## Testing
- [x] try the feature, event with a custom notification config
- [x] The documentation is complete on community.sensenet.com/docs

### todo
- [ ] Talk to Joe about their solution and discuss feature requests
- [ ] Check the documentation if it makes sense

**Comment by iviczl** [comment]
Joe's feature requests foretells future must have functions. For a notification the client wants to set:
- affected content types
- separate events to notify on or not
- recipient users
