### ISSUE TITLE
[Components]: DocViewer

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sensenet#78]
Create a repository for the **Document viewer** component and publish it as _NuGet_ and/or _npm_ packages. 
> **Note**: this is the user-facing viewer plugin, not the preview generator, which is an enterprise component and published differently.

- [ ] a JS plugin that can be used with the Services layer
- [ ] *hide* the Preview action in WebPages component but retain the old JS and ascx files so that it can be switched on manually.
- [ ] Refactor/rewrite the js plugin (remove jquery and other unnecessary dependencies, etc) in TypeScript and React(?)
- [ ] plugin can be used as a standalone viewer without sensenet

## Tasks / Progress

 - [x] Pager widget (jump to fist / prev / next / last / specified page)
 - [ ] Shapes
     - [x] Delete shape from keyboard
     - [x] Recalculate shape positions on rotation
     - [ ] Note formatting and updating
     - [ ] Create new shape
 - [x] Config 
     - [x] Endpoint for localized string resources
 - [x] DocumentViewerError component - localizable error messages instead of response dump
 - [x] Testing & docs
     - [x] Enable *completed-docs* linting rule, fix all linting errors
     - [x] Coverage to 80%+
 - [x] Finializing
     - [x] publish example app to Netlify
